##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /fi_test
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Fashioning Insurrection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Costumes of a world in revolution.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "CollectionBuilder-CSV is a template for creating digital collection exhibits using static web technology."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: fashion; insurrection; brown university; brown university library; revolution
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Brown University Library

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: test_fi_data
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Brown University Library"
organization-link: https://library.brown.edu

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed

hierarchy:
  - short-title: Greek War
    title: Greek War of Independence
    img: /img/greekcostume.jpg
    imgalt: greek costume
    time: 1821 - 1829
    color: "#425371"
    transparentcolor: "rgba(66, 83, 113, 0.7)"
    dkcolor: "#202c41"
    arch: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20999%22%3E%3Cpath%20d%3D%22%20%20%20%20%20%20M-50%20-50%20%20%20%20%20%20H250%20%20%20%20%20%20V2000%20%20%20%20%20%20H190%20%20%20%20%20%20V100%20%20%20%20%20%20q0%20-90%20-90%20-90%20%20%20%20%20%20t-90%2090%20%20%20%20%20%20V2000%20%20%20%20%20%20H-50%20%20%20%20%20%20z%22%2F%3E%3C%2Fsvg%3E"
    children:
      - page: Navigating Characters and Costumes of the Greek War of Independence
        url: /greece/characters-and-costumes/
        caseid: 1
      - page: "Philhellenism: Americans in Support of the Greek Revolution and in Greek Costume"
        url: /greece/philhellenism/
        caseid: 2
  - title: Early Algerian Resistance
    short-title: Algerian Resistance
    img: /img/algeriancostume.jpg
    imgalt: algerian costume
    time: 1830 - c.1850
    color: "#878581"
    transparentcolor: "rgba(135, 133, 129, 0.7)"
    dkcolor: "#494337"
    arch: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22200%22%20height%3D%221000%22%20viewBox%3D%220%200%20200%201000%22%3E%3Cpath%20d%3D%22%20%20M-50%20-50%20%20h400%20%20v1500%20%20H190%20%20V104%20%20l-5%20-5%20%20q30%20-60%20-85%20-90%20%20q-110%2020%20-85%2090%20%20l-5%205%20%20V1500%20%20H-200%20%20z%22%2F%3E%3C%2Fsvg%3E"
    children:
      - page: Costumes and Customs Documented Through Barbary Captivity and Trade Accounts
        url: /algeria/costumes-and-customs/
        caseid: 3
      - page: "Aftermath and Adaptation: Abd el-Kader to the Zouaves and Turcos in Popular Print"
        url: /algeria/aftermath-and-adaptation/
        caseid: 4
      - page: Orientalist Legacies of Algeria in the American Civil War
        url: /algeria/orientalist-legacies/
        caseid: 5
  - short-title: Indian Uprising
    title: Indian Uprising
    time: 1857 - 1858
    img: /img/indiancostume.jpg
    imgalt: indian costume
    color: "#7d3223"
    transparentcolor: "rgba(125, 50, 35, 0.7)"
    dkcolor: "#452214"
    arch: "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22200%22%20height%3D%221000%22%20viewBox%3D%220%200%20200%201000%22%3E%3Cpath%20d%3D%22%20%20M-50%20-50%20%20h400%20%20v1500%20%20H190%20%20V94%20%20q0%20-65%20-90%20-85%20%20q-90%2015%20-90%2085%20%20v1500%20%20h-100%20%20z%22%2F%3E%3C%2Fsvg%3E"
    children:
      - page: Resisting the Spread of the British East India Company across the Subcontinent
        url: /india/resisting-the-spread-of-the-british-east-india-company/
        caseid: 6
      - page: 1857 Uprising in Press and Popular Sentiment
        url: /india/press-and-popular-sentiment/
        caseid: 7
